//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanClient.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HangmanClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string btnJoin {
            get {
                return ResourceManager.GetString("btnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string btnJoinMatch {
            get {
                return ResourceManager.GetString("btnJoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva Partida.
        /// </summary>
        public static string btnNewMatch {
            get {
                return ResourceManager.GetString("btnNewMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string btnRegister {
            get {
                return ResourceManager.GetString("btnRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comenzar.
        /// </summary>
        public static string btnStart {
            get {
                return ResourceManager.GetString("btnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas disponibles.
        /// </summary>
        public static string lbAvailableMatches {
            get {
                return ResourceManager.GetString("lbAvailableMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Categoría: .
        /// </summary>
        public static string lbCategory {
            get {
                return ResourceManager.GetString("lbCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string lbChat {
            get {
                return ResourceManager.GetString("lbChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha de nacimiento.
        /// </summary>
        public static string lbDateOfBirth {
            get {
                return ResourceManager.GetString("lbDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inglés.
        /// </summary>
        public static string lbLanguajeEnglish {
            get {
                return ResourceManager.GetString("lbLanguajeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string lbLanguajeSpanish {
            get {
                return ResourceManager.GetString("lbLanguajeSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno.
        /// </summary>
        public static string lbLastName {
            get {
                return ResourceManager.GetString("lbLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string lbLastName_Mother_ {
            get {
                return ResourceManager.GetString("lbLastName(Mother)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string lbLeave {
            get {
                return ResourceManager.GetString("lbLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat .
        /// </summary>
        public static string lbLiveChat {
            get {
                return ResourceManager.GetString("lbLiveChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string lbLogIn {
            get {
                return ResourceManager.GetString("lbLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lblPassword {
            get {
                return ResourceManager.GetString("lblPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Creada por: .
        /// </summary>
        public static string lbMadeBy {
            get {
                return ResourceManager.GetString("lbMadeBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas.
        /// </summary>
        public static string lbMatches {
            get {
                return ResourceManager.GetString("lbMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Partida: .
        /// </summary>
        public static string lbMatchId {
            get {
                return ResourceManager.GetString("lbMatchId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string lbName {
            get {
                return ResourceManager.GetString("lbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ó.
        /// </summary>
        public static string lbOr {
            get {
                return ResourceManager.GetString("lbOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        public static string lbPhone {
            get {
                return ResourceManager.GetString("lbPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string lbSignUp {
            get {
                return ResourceManager.GetString("lbSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total: .
        /// </summary>
        public static string lbTotal {
            get {
                return ResourceManager.GetString("lbTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string lbUsername {
            get {
                return ResourceManager.GetString("lbUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando a rival....
        /// </summary>
        public static string lbWaitingOpponent {
            get {
                return ResourceManager.GetString("lbWaitingOpponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido(a): .
        /// </summary>
        public static string lbWelcome {
            get {
                return ResourceManager.GetString("lbWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Palabra: .
        /// </summary>
        public static string lbWord {
            get {
                return ResourceManager.GetString("lbWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar idioma.
        /// </summary>
        public static string ttChangeLanguaje {
            get {
                return ResourceManager.GetString("ttChangeLanguaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi puntaje.
        /// </summary>
        public static string ttMyPoints {
            get {
                return ResourceManager.GetString("ttMyPoints", resourceCulture);
            }
        }
    }
}
