//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanClient.ScoreServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayerScoreDTO", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class PlayerScoreDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesLostField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchesWonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PenaltiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesLost {
            get {
                return this.MatchesLostField;
            }
            set {
                if ((this.MatchesLostField.Equals(value) != true)) {
                    this.MatchesLostField = value;
                    this.RaisePropertyChanged("MatchesLost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchesWon {
            get {
                return this.MatchesWonField;
            }
            set {
                if ((this.MatchesWonField.Equals(value) != true)) {
                    this.MatchesWonField = value;
                    this.RaisePropertyChanged("MatchesWon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Penalties {
            get {
                return this.PenaltiesField;
            }
            set {
                if ((this.PenaltiesField.Equals(value) != true)) {
                    this.PenaltiesField = value;
                    this.RaisePropertyChanged("Penalties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalScore {
            get {
                return this.TotalScoreField;
            }
            set {
                if ((this.TotalScoreField.Equals(value) != true)) {
                    this.TotalScoreField = value;
                    this.RaisePropertyChanged("TotalScore");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchHistoryDTO", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class MatchHistoryDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RivalUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Points {
            get {
                return this.PointsField;
            }
            set {
                if ((this.PointsField.Equals(value) != true)) {
                    this.PointsField = value;
                    this.RaisePropertyChanged("Points");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RivalUsername {
            get {
                return this.RivalUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.RivalUsernameField, value) != true)) {
                    this.RivalUsernameField = value;
                    this.RaisePropertyChanged("RivalUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordText {
            get {
                return this.WordTextField;
            }
            set {
                if ((object.ReferenceEquals(this.WordTextField, value) != true)) {
                    this.WordTextField = value;
                    this.RaisePropertyChanged("WordText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScoreServiceRef.IScoreService")]
    public interface IScoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScoreService/GetPlayerScore", ReplyAction="http://tempuri.org/IScoreService/GetPlayerScoreResponse")]
        HangmanClient.ScoreServiceRef.PlayerScoreDTO GetPlayerScore(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScoreService/GetPlayerScore", ReplyAction="http://tempuri.org/IScoreService/GetPlayerScoreResponse")]
        System.Threading.Tasks.Task<HangmanClient.ScoreServiceRef.PlayerScoreDTO> GetPlayerScoreAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScoreService/GetMatchHistory", ReplyAction="http://tempuri.org/IScoreService/GetMatchHistoryResponse")]
        HangmanClient.ScoreServiceRef.MatchHistoryDTO[] GetMatchHistory(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScoreService/GetMatchHistory", ReplyAction="http://tempuri.org/IScoreService/GetMatchHistoryResponse")]
        System.Threading.Tasks.Task<HangmanClient.ScoreServiceRef.MatchHistoryDTO[]> GetMatchHistoryAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScoreServiceChannel : HangmanClient.ScoreServiceRef.IScoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScoreServiceClient : System.ServiceModel.ClientBase<HangmanClient.ScoreServiceRef.IScoreService>, HangmanClient.ScoreServiceRef.IScoreService {
        
        public ScoreServiceClient() {
        }
        
        public ScoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HangmanClient.ScoreServiceRef.PlayerScoreDTO GetPlayerScore(int userId) {
            return base.Channel.GetPlayerScore(userId);
        }
        
        public System.Threading.Tasks.Task<HangmanClient.ScoreServiceRef.PlayerScoreDTO> GetPlayerScoreAsync(int userId) {
            return base.Channel.GetPlayerScoreAsync(userId);
        }
        
        public HangmanClient.ScoreServiceRef.MatchHistoryDTO[] GetMatchHistory(int userId) {
            return base.Channel.GetMatchHistory(userId);
        }
        
        public System.Threading.Tasks.Task<HangmanClient.ScoreServiceRef.MatchHistoryDTO[]> GetMatchHistoryAsync(int userId) {
            return base.Channel.GetMatchHistoryAsync(userId);
        }
    }
}
