sonar.projectKey=hangmanCliente
sonar.working.directory=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient
sonar.pullrequest.cache.basepath=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient

DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.projectKey=hangmanCliente:DF9688BF-49BD-4C74-B7F0-A6B57F603574
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.projectName=HangmanClient
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.projectBaseDir=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.sourceEncoding=utf-8
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.tests=
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.sources=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\App.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\CreateMatch.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\JoinMatch.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\MainMenu.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Match.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\SignUp.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\UserSession.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\App.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Login.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\MainWindow.xaml.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\AssemblyInfo.cs",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Resources.resx",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Resources.en.resx",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\AccountService.wsdl",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\AccountService.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\AccountService1.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\AccountService2.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\HangmanClient.AccountServiceRef.UserDTO.datasource",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\CatalogService.wsdl",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\CatalogService.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\CatalogService1.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\CatalogService2.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\HangmanClient.CatalogServiceRef.CategoryDTO.datasource",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\HangmanClient.CatalogServiceRef.WordDTO.datasource",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\GameService.wsdl",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\GameService.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\GameService1.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\GameService2.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\GameService3.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\HangmanClient.MatchmakingServiceRef.AvailableMatchDTO.datasource",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\MatchmakingService.wsdl",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\MatchmakingService.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\MatchmakingService1.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\MatchmakingService2.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\HangmanClient.ScoreServiceRef.MatchHistoryDTO.datasource",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\HangmanClient.ScoreServiceRef.PlayerScoreDTO.datasource",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\ScoreService.wsdl",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\ScoreService.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\ScoreService1.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\ScoreService2.xsd",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Settings.settings",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\App.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\AccountService.disco",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\configuration91.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\configuration.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\AccountServiceRef\\Reference.svcmap",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\MatchmakingService.disco",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\configuration91.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\configuration.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\MatchmakingServiceRef\\Reference.svcmap",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\CatalogService.disco",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\configuration91.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\configuration.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\CatalogServiceRef\\Reference.svcmap",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\GameService.disco",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\configuration91.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\configuration.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\GameServiceRef\\Reference.svcmap",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\ScoreService.disco",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\configuration91.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\configuration.svcinfo",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Connected Services\\ScoreServiceRef\\Reference.svcmap",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\CreateMatch.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\JoinMatch.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Login.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\MainMenu.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\MainWindow.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Match.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Styles\\GlobalStyles.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\SignUp.xaml",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\Menu.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\Login.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\Match.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\Game.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\brazoDer.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\brazoIzq.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\cabeza.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\cuerpo.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\piernaDer.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\piernaIzq.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\editProfile.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\languaje.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\myPoints.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\chat.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\head.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\leftArm.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\leftLeg.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\rightArm.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\rightLeg.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\body.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\Properties\\Images\\logOut.png",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.vs\\HangmanClient.csproj.dtbcache.json",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\bin\\Debug\\HangmanClient.exe.config",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.vs\\HangmanClient\\v17\\DocumentLayout.backup.json",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.vs\\HangmanClient\\v17\\DocumentLayout.json",\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.vs\\HangmanClient\\v17\\ResourceExplorer\\settings.json"

DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.cs.analyzer.projectOutPaths=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.sonarqube\\out\\1"
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.cs.roslyn.reportFilePaths=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.sonarqube\\out\\1\\Issues.json"
DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.cs.scanner.telemetry=\
"C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.sonarqube\\out\\1\\Telemetry.json"

DF9688BF-49BD-4C74-B7F0-A6B57F603574.sonar.working.directory=C:\\Users\\migue\\OneDrive\\Escritorio\\HangmanClient\\.sonarqube\\out\\.sonar\\mod0
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=DF9688BF-49BD-4C74-B7F0-A6B57F603574

