//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanClient.GameServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameContextDTO", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class GameContextDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChallengerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreatorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WordDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WordLengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChallengerId {
            get {
                return this.ChallengerIdField;
            }
            set {
                if ((this.ChallengerIdField.Equals(value) != true)) {
                    this.ChallengerIdField = value;
                    this.RaisePropertyChanged("ChallengerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreatorId {
            get {
                return this.CreatorIdField;
            }
            set {
                if ((this.CreatorIdField.Equals(value) != true)) {
                    this.CreatorIdField = value;
                    this.RaisePropertyChanged("CreatorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretWord {
            get {
                return this.SecretWordField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretWordField, value) != true)) {
                    this.SecretWordField = value;
                    this.RaisePropertyChanged("SecretWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WordDescription {
            get {
                return this.WordDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.WordDescriptionField, value) != true)) {
                    this.WordDescriptionField = value;
                    this.RaisePropertyChanged("WordDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordLength {
            get {
                return this.WordLengthField;
            }
            set {
                if ((this.WordLengthField.Equals(value) != true)) {
                    this.WordLengthField = value;
                    this.RaisePropertyChanged("WordLength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TurnResultDTO", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class TurnResultDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] CorrectPositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentMistakesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char GuessedLetterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCorrectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] CorrectPositions {
            get {
                return this.CorrectPositionsField;
            }
            set {
                if ((object.ReferenceEquals(this.CorrectPositionsField, value) != true)) {
                    this.CorrectPositionsField = value;
                    this.RaisePropertyChanged("CorrectPositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentMistakes {
            get {
                return this.CurrentMistakesField;
            }
            set {
                if ((this.CurrentMistakesField.Equals(value) != true)) {
                    this.CurrentMistakesField = value;
                    this.RaisePropertyChanged("CurrentMistakes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char GuessedLetter {
            get {
                return this.GuessedLetterField;
            }
            set {
                if ((this.GuessedLetterField.Equals(value) != true)) {
                    this.GuessedLetterField = value;
                    this.RaisePropertyChanged("GuessedLetter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCorrect {
            get {
                return this.IsCorrectField;
            }
            set {
                if ((this.IsCorrectField.Equals(value) != true)) {
                    this.IsCorrectField = value;
                    this.RaisePropertyChanged("IsCorrect");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameEndDTO", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class GameEndDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PenalizedUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HangmanClient.GameServiceRef.MatchEndReason ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WinnerIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PenalizedUserId {
            get {
                return this.PenalizedUserIdField;
            }
            set {
                if ((this.PenalizedUserIdField.Equals(value) != true)) {
                    this.PenalizedUserIdField = value;
                    this.RaisePropertyChanged("PenalizedUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HangmanClient.GameServiceRef.MatchEndReason Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((this.ReasonField.Equals(value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WinnerId {
            get {
                return this.WinnerIdField;
            }
            set {
                if ((this.WinnerIdField.Equals(value) != true)) {
                    this.WinnerIdField = value;
                    this.RaisePropertyChanged("WinnerId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatchEndReason", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    public enum MatchEndReason : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WordGuessed = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaxMistakesReached = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Abandoned = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timeout = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GameServiceRef.IGameService", CallbackContract=typeof(HangmanClient.GameServiceRef.IGameServiceCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IGameService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/JoinGameChannel")]
        void JoinGameChannel(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/JoinGameChannel")]
        System.Threading.Tasks.Task JoinGameChannelAsync(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendGuess")]
        void SendGuess(int matchId, int userId, char guessLetter);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendGuess")]
        System.Threading.Tasks.Task SendGuessAsync(int matchId, int userId, char guessLetter);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SubmitTurnResult")]
        void SubmitTurnResult(int matchId, int userId, bool isCorrect, int[] correctPositions);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SubmitTurnResult")]
        System.Threading.Tasks.Task SubmitTurnResultAsync(int matchId, int userId, bool isCorrect, int[] correctPositions);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/LeaveMatch")]
        void LeaveMatch(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/LeaveMatch")]
        System.Threading.Tasks.Task LeaveMatchAsync(int matchId, int userId);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendChatMessage")]
        void SendChatMessage(int matchId, string senderUsername, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/SendChatMessage")]
        System.Threading.Tasks.Task SendChatMessageAsync(int matchId, string senderUsername, string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnGameStarted")]
        void OnGameStarted(HangmanClient.GameServiceRef.GameContextDTO gameContext);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnGuessReceived")]
        void OnGuessReceived(char guessedLetter);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnTurnResultReceived")]
        void OnTurnResultReceived(HangmanClient.GameServiceRef.TurnResultDTO turnResult);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnGameEnded")]
        void OnGameEnded(HangmanClient.GameServiceRef.GameEndDTO endResult);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnTimerTick")]
        void OnTimerTick(int secondsLeft);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnChatMessageReceived")]
        void OnChatMessageReceived(string senderUsername, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGameService/OnEvaluationError")]
        void OnEvaluationError();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGameServiceChannel : HangmanClient.GameServiceRef.IGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GameServiceClient : System.ServiceModel.DuplexClientBase<HangmanClient.GameServiceRef.IGameService>, HangmanClient.GameServiceRef.IGameService {
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void JoinGameChannel(int matchId, int userId) {
            base.Channel.JoinGameChannel(matchId, userId);
        }
        
        public System.Threading.Tasks.Task JoinGameChannelAsync(int matchId, int userId) {
            return base.Channel.JoinGameChannelAsync(matchId, userId);
        }
        
        public void SendGuess(int matchId, int userId, char guessLetter) {
            base.Channel.SendGuess(matchId, userId, guessLetter);
        }
        
        public System.Threading.Tasks.Task SendGuessAsync(int matchId, int userId, char guessLetter) {
            return base.Channel.SendGuessAsync(matchId, userId, guessLetter);
        }
        
        public void SubmitTurnResult(int matchId, int userId, bool isCorrect, int[] correctPositions) {
            base.Channel.SubmitTurnResult(matchId, userId, isCorrect, correctPositions);
        }
        
        public System.Threading.Tasks.Task SubmitTurnResultAsync(int matchId, int userId, bool isCorrect, int[] correctPositions) {
            return base.Channel.SubmitTurnResultAsync(matchId, userId, isCorrect, correctPositions);
        }
        
        public void LeaveMatch(int matchId, int userId) {
            base.Channel.LeaveMatch(matchId, userId);
        }
        
        public System.Threading.Tasks.Task LeaveMatchAsync(int matchId, int userId) {
            return base.Channel.LeaveMatchAsync(matchId, userId);
        }
        
        public void SendChatMessage(int matchId, string senderUsername, string message) {
            base.Channel.SendChatMessage(matchId, senderUsername, message);
        }
        
        public System.Threading.Tasks.Task SendChatMessageAsync(int matchId, string senderUsername, string message) {
            return base.Channel.SendChatMessageAsync(matchId, senderUsername, message);
        }
    }
}
