//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangmanClient.MatchmakingServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AvailableMatchDTO", Namespace="http://schemas.datacontract.org/2004/07/HangmanServer.DTOs")]
    [System.SerializableAttribute()]
    public partial class AvailableMatchDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ChallengerUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreatorUsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MatchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StatusIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryName {
            get {
                return this.CategoryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryNameField, value) != true)) {
                    this.CategoryNameField = value;
                    this.RaisePropertyChanged("CategoryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChallengerUsername {
            get {
                return this.ChallengerUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.ChallengerUsernameField, value) != true)) {
                    this.ChallengerUsernameField = value;
                    this.RaisePropertyChanged("ChallengerUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatorUsername {
            get {
                return this.CreatorUsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorUsernameField, value) != true)) {
                    this.CreatorUsernameField = value;
                    this.RaisePropertyChanged("CreatorUsername");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MatchId {
            get {
                return this.MatchIdField;
            }
            set {
                if ((this.MatchIdField.Equals(value) != true)) {
                    this.MatchIdField = value;
                    this.RaisePropertyChanged("MatchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StatusId {
            get {
                return this.StatusIdField;
            }
            set {
                if ((this.StatusIdField.Equals(value) != true)) {
                    this.StatusIdField = value;
                    this.RaisePropertyChanged("StatusId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MatchmakingServiceRef.IMatchmakingService")]
    public interface IMatchmakingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/CreateMatch", ReplyAction="http://tempuri.org/IMatchmakingService/CreateMatchResponse")]
        int CreateMatch(string username, string categoryName, string wordText, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/CreateMatch", ReplyAction="http://tempuri.org/IMatchmakingService/CreateMatchResponse")]
        System.Threading.Tasks.Task<int> CreateMatchAsync(string username, string categoryName, string wordText, string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchmakingService/GetAvailableMatchesResponse")]
        HangmanClient.MatchmakingServiceRef.AvailableMatchDTO[] GetAvailableMatches(string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/GetAvailableMatches", ReplyAction="http://tempuri.org/IMatchmakingService/GetAvailableMatchesResponse")]
        System.Threading.Tasks.Task<HangmanClient.MatchmakingServiceRef.AvailableMatchDTO[]> GetAvailableMatchesAsync(string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/GetMatchStatus", ReplyAction="http://tempuri.org/IMatchmakingService/GetMatchStatusResponse")]
        HangmanClient.MatchmakingServiceRef.AvailableMatchDTO GetMatchStatus(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/GetMatchStatus", ReplyAction="http://tempuri.org/IMatchmakingService/GetMatchStatusResponse")]
        System.Threading.Tasks.Task<HangmanClient.MatchmakingServiceRef.AvailableMatchDTO> GetMatchStatusAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/JoinMatch", ReplyAction="http://tempuri.org/IMatchmakingService/JoinMatchResponse")]
        bool JoinMatch(int matchId, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/JoinMatch", ReplyAction="http://tempuri.org/IMatchmakingService/JoinMatchResponse")]
        System.Threading.Tasks.Task<bool> JoinMatchAsync(int matchId, string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/StartMatch", ReplyAction="http://tempuri.org/IMatchmakingService/StartMatchResponse")]
        bool StartMatch(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/StartMatch", ReplyAction="http://tempuri.org/IMatchmakingService/StartMatchResponse")]
        System.Threading.Tasks.Task<bool> StartMatchAsync(int matchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/LeaveMatch", ReplyAction="http://tempuri.org/IMatchmakingService/LeaveMatchResponse")]
        bool LeaveMatch(int matchId, bool isCreator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/LeaveMatch", ReplyAction="http://tempuri.org/IMatchmakingService/LeaveMatchResponse")]
        System.Threading.Tasks.Task<bool> LeaveMatchAsync(int matchId, bool isCreator);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/GetUserIdByUsername", ReplyAction="http://tempuri.org/IMatchmakingService/GetUserIdByUsernameResponse")]
        int GetUserIdByUsername(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMatchmakingService/GetUserIdByUsername", ReplyAction="http://tempuri.org/IMatchmakingService/GetUserIdByUsernameResponse")]
        System.Threading.Tasks.Task<int> GetUserIdByUsernameAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMatchmakingServiceChannel : HangmanClient.MatchmakingServiceRef.IMatchmakingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MatchmakingServiceClient : System.ServiceModel.ClientBase<HangmanClient.MatchmakingServiceRef.IMatchmakingService>, HangmanClient.MatchmakingServiceRef.IMatchmakingService {
        
        public MatchmakingServiceClient() {
        }
        
        public MatchmakingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MatchmakingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MatchmakingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CreateMatch(string username, string categoryName, string wordText, string languageCode) {
            return base.Channel.CreateMatch(username, categoryName, wordText, languageCode);
        }
        
        public System.Threading.Tasks.Task<int> CreateMatchAsync(string username, string categoryName, string wordText, string languageCode) {
            return base.Channel.CreateMatchAsync(username, categoryName, wordText, languageCode);
        }
        
        public HangmanClient.MatchmakingServiceRef.AvailableMatchDTO[] GetAvailableMatches(string languageCode) {
            return base.Channel.GetAvailableMatches(languageCode);
        }
        
        public System.Threading.Tasks.Task<HangmanClient.MatchmakingServiceRef.AvailableMatchDTO[]> GetAvailableMatchesAsync(string languageCode) {
            return base.Channel.GetAvailableMatchesAsync(languageCode);
        }
        
        public HangmanClient.MatchmakingServiceRef.AvailableMatchDTO GetMatchStatus(int matchId) {
            return base.Channel.GetMatchStatus(matchId);
        }
        
        public System.Threading.Tasks.Task<HangmanClient.MatchmakingServiceRef.AvailableMatchDTO> GetMatchStatusAsync(int matchId) {
            return base.Channel.GetMatchStatusAsync(matchId);
        }
        
        public bool JoinMatch(int matchId, string username) {
            return base.Channel.JoinMatch(matchId, username);
        }
        
        public System.Threading.Tasks.Task<bool> JoinMatchAsync(int matchId, string username) {
            return base.Channel.JoinMatchAsync(matchId, username);
        }
        
        public bool StartMatch(int matchId) {
            return base.Channel.StartMatch(matchId);
        }
        
        public System.Threading.Tasks.Task<bool> StartMatchAsync(int matchId) {
            return base.Channel.StartMatchAsync(matchId);
        }
        
        public bool LeaveMatch(int matchId, bool isCreator) {
            return base.Channel.LeaveMatch(matchId, isCreator);
        }
        
        public System.Threading.Tasks.Task<bool> LeaveMatchAsync(int matchId, bool isCreator) {
            return base.Channel.LeaveMatchAsync(matchId, isCreator);
        }
        
        public int GetUserIdByUsername(string username) {
            return base.Channel.GetUserIdByUsername(username);
        }
        
        public System.Threading.Tasks.Task<int> GetUserIdByUsernameAsync(string username) {
            return base.Channel.GetUserIdByUsernameAsync(username);
        }
    }
}
